# **Practice Activity - Pandas Series**

**Introduction:**
A pandas Series is a one-dimensional array. It holds any data type supported in Python and uses labels to locate each data value for retrieval. These labels form the index, and they can be strings or integers. A Series is the main data structure in the pandas framework for storing one-dimensional data.

**Common methods used with Pandas Series**


Please refer to the [Pandas Series Documentation](https://pandas.pydata.org/docs/reference/api/pandas.Series.html) for a full list of methods and how to implement them.

To complete the problems below we first need to import the Pandas and Numpy libraries. If you haven't already installed them, use pip or conda to install them globally or in your virtual environment.


* The common alias for pandas is pd.  
* The common alias for numpy is np.

In [1]:
#pip install pandas
#pip install numpy

import pandas as pd
import numpy as np

**Problem 1**

We can easily convert lists, tuples, dictionaries and numpy arrays into a Pandas Series by directly passing the python object as an arguement to the Series() constructor. We have used the alias pd in the cell above, so we will use pd.Series() to construct our Series object.



*  Convert the 3 objects below into 3 seperate Pandas Series objects.
*  Use the .head() method to see the first 5 items in each Series

In [13]:


mylist = list('abcedfghijklmnopqrstuvwxyz') # Converts the string of letters into a list of individual characters.
myarr = np.arange(26) # Creates a NumPy array of numbers from 0 to 25.
mydict = dict(zip(mylist, myarr)) # Combines the list and array into key-value pairs to create a dictionary mapping each letter to a number.
print(mydict)

series1 = pd.Series(mylist)
print(series1.head())
series2 = pd.Series(myarr)
print(series2.head())
series3 = pd.Series(mydict)
print(series3.head())

{'a': np.int64(0), 'b': np.int64(1), 'c': np.int64(2), 'e': np.int64(3), 'd': np.int64(4), 'f': np.int64(5), 'g': np.int64(6), 'h': np.int64(7), 'i': np.int64(8), 'j': np.int64(9), 'k': np.int64(10), 'l': np.int64(11), 'm': np.int64(12), 'n': np.int64(13), 'o': np.int64(14), 'p': np.int64(15), 'q': np.int64(16), 'r': np.int64(17), 's': np.int64(18), 't': np.int64(19), 'u': np.int64(20), 'v': np.int64(21), 'w': np.int64(22), 'x': np.int64(23), 'y': np.int64(24), 'z': np.int64(25)}
0    a
1    b
2    c
3    e
4    d
dtype: object
0    0
1    1
2    2
3    3
4    4
dtype: int64
a    0
b    1
c    2
e    3
d    4
dtype: int64

**Problem 2**

We can give a name to our Pandas series as a parameter of our Constructor method.

*   Use the name parameter to add 'alphabet' as the name of our series.
*   Use the .head() method to see the name of our Series displayed

In [14]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'), name='alphabet')
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabet, dtype: object

**Problem 3: Assign a name to the Series**

We can assign a name to a Series after it is created using the `.name` attribute on our Series object.



*   Use the `.name` attribute to add the name 'alphabet1' to the Series object after it has been created.
*   Use the .head() method to verify

In [16]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'alphabet1'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabet1, dtype: object

**Problem 4**

We can use mathematic operators to perform calculations on two or more series.

*   Create a new object that adds the two series below
*   Create a new object that subtracts the two series below
*   Create a new object that multiplies the two series below
*   Create a new object that divides the two series below

Make sure you display your outputs.

In [17]:
ser1= pd.Series([2, 4, 6, 8, 10])
ser2= pd.Series([1, 3, 5, 7, 9])

addition = ser1 + ser2
print(addition)
subtraction = ser1 - ser2
print(subtraction)
multiplication = ser1* ser2
print(multiplication)
division = ser1 / ser2
print(division)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

**Problem 5**

We can use comparison operators to compare elements of two Series.

Use the series below to perform the following:


*   Check if the elements in ser1 are equal to the elements in ser2
*   Check if the elements in ser1 are greater than the elements in ser2
*   Check if the elements in ser1 are less than the elements in ser2

In [18]:
ser1= pd.Series([2, 4, 5, 8, 10])
ser2= pd.Series([1, 3, 5, 7, 10])

equal = ser1 == ser2
print(equal)
mayor = ser1 > ser2
print(mayor)
minor = ser1 < ser2
print(minor)

0    False
1    False
2     True
3    False
4     True
dtype: bool
0     True
1     True
2    False
3     True
4    False
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool

**Problem 6**

We can add additional elements to our Pandas Series. Use the Series below to perform the following:


*   Create a new Series by using the `.concat()` method to add 'penguin' and 'lion' to the Series object
*   Use the `.reset_index()` method to reset the index values.

(Both steps can be done in one line)

In [23]:
ser= pd.Series(['cat', 'dog', 'elephant', 'frog'])
new_items = pd.Series(['penguin', 'lion'])
new_ser = pd.concat([ser, new_items]).reset_index(drop=True)
print(new_ser)

0         cat
1         dog
2    elephant
3        frog
4     penguin
5        lion
dtype: object

**Problem 7**

We can customize the index of our Series by using the 'index' paramater in our Series constructor. Use the Series below to peform the following:


*   Set the index to ['A', 'B', 'C', 'D']
*   Use the .reindex() method after the Series object is created to change the order of the index to ['B', 'A', 'D', 'C']

In [26]:
ser= pd.Series(['cat', 'dog', 'elephant', 'frog'], index = ['A', 'B', 'C', 'D'])
sorted = ser.reindex(['D','C', 'B', 'A'])
print(ser)
print(sorted)

A         cat
B         dog
C    elephant
D        frog
dtype: object
D        frog
C    elephant
B         dog
A         cat
dtype: object

**Problem 8**

Find the elements in the first series (ser1) not in the second series (ser2).


*   Use the single square bracket notation and the .isin() method with ser1 to remove the items present in ser2. This will leave us with only the items not present in ser2.

In [27]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser3 = [ser1.isin(ser2)]
print(ser3)

[0    False
1    False
2    False
3     True
4     True
dtype: bool]

**Problem 9**

Use the Series below to peform the following:
*   Use a built-in Pandas method to find the mean of the Series
*   Use a built-in Pandas method to find the standard deviation of the Series

In [ ]:
ser = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])

**Problem 10**

Find the elements in both series that are not in common (remove them if they exist in both).

*   Create a new Series using np.union1d()
*   Create a new Series using np. intersect1d()
*   Use single square bracket notation and the .isin() method to find the final result

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

**Problem 11**

Find the minimum, max, 25th percentile, and 75th percentile in the series.

*   Use np.percentile to find the percentiles above

In [ ]:
ser = pd.Series(np.random.normal(10, 5, 25))

**Problem 12**

Obtain the count of each unique item in the series.


*   Use the .value_counts() method to find the frequency count of each unique item

In [ ]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

**Problem 13**

Keep the two most frequent items in the series and change all items that are not those two into "Other".



*   Use .isin(), .valuecounts(), and .index() to complete the task above

In [ ]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

**Problem 14**

Bin the series below into 10 equal deciles and replace the values with the bin name.

*   Use the .qcut() method to complete the task

In [ ]:
ser = pd.Series(np.random.random(20))

**Problem 15**

From ser, extract the items at positions in list pos.

*   Use the .take() method to complete the task

In [ ]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

**Problem 16**

Stack ser1 and ser2 vertically.

*   Use the .concat() method to complete the task

In [ ]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

**Problem 17**

Get the positions of items of ser2 in ser1 as a list.

*   Use list comprehension, pd.Index, and .getloc() to complete the task

In [ ]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

**Problem 18**

Caluculate the difference of differences between the consequtive numbers of ser. Dislplay the output as a list.

*   Use the .diff() method to the complete the task

In [ ]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

**Problem 19**

Convert the date-strings to a timeseries.

*   use the .to_datetime() method to complete the task

In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

**Problem 20**

Compute the mean of weights of each fruit.

In [ ]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weight.tolist())
print(fruit.tolist())
#examples
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

##**Submission**
- Submit your completed lab using the Start Assignment button on the assignment page in Canvas.
- Your submission can be include:
  - if you are using notebook then, all tasks should be written and submitted in a single notebook file, for example: (**your_name_labname.ipynb**).
  - if you are using python script file, all tasks should be written and submitted in a single python script file for example: **(your_name_labname.py)**.
- Add appropriate comments and any additional instructions if required.